name: Setup, Test, Build, Code Analysis, Containerize and Deploy

on:
    push:
        branches:
            - master

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: ${{ secrets.RUN_PROJECT }}
    RUN_REGION: us-central1
    SERVICE_NAME: super-simple-service

jobs:
    setup-build-deploy:
        name: Setup, Test, Build, Code Analysis, Containerize and Deploy
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [10.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Setup gcloud CLI
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: '290.0.1'
                  service_account_key: ${{ secrets.RUN_SA_KEY }}
                  project_id: ${{ secrets.RUN_PROJECT }}

            # Build and unit test
            - name: Unit Test and Build
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm test
            - run: npm install --production

            # SonarQube Analysis
            - name: Code Analysis with Sonar Scan
              uses: kitabisa/sonarqube-action@master
              with:
                host: ${{ secrets.SONARQUBE_HOST }}
                login: ${{ secrets.SONARQUBE_TOKEN }}

            # Build and push image to Google Container Registry
            - name: Docker build and publish to GCR
              run: |-
                gcloud builds submit \
                  --quiet \
                  --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
            
            # Deploy image to Cloud Run
            - name: Deploy to CloudRun
              run: |-
                gcloud run deploy "$SERVICE_NAME" \
                  --quiet \
                  --region "$RUN_REGION" \
                  --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
                  --platform "managed" \
                  --allow-unauthenticated
